### PR TITLE
Prepare to release v0.8.0

### PR DESCRIPTION
**Pull request by shishirb-MSFT**
* agent, sdk: 0.6.0
* plugin-apt: 0.4.0

### CODE REVIEW

**Comment by shishirb-MSFT** [comment]
I expect some changes to come after testing with the DU yocto build. Wait for further iterations.

**Comment by shishirb-MSFT** [comment]
Tested ubuntu 1804 packages for both the fresh install and upgrade scenario. Any further changes will be done as patch releases.

---
In reply to: [929331828](https://github.com/microsoft/do-client/pull/84#issuecomment-929331828) [](http://example.com/codeflow?ancestors=929331828)

**Comment by jimson-msft** [comment]
Not going to wait for the platform agnostic header change? Keep in mind this will break DU builds unless we notify them that they need to add the appropriate DO_INTERFACE_REST and DO_CLIENT_AGENT flags (may also break mariner builds when they adopt)

**Comment by shishirb-MSFT** [comment]
Oops, forgot about it. I'll wait.

---
In reply to: [929538113](https://github.com/microsoft/do-client/pull/84#issuecomment-929538113) [](http://example.com/codeflow?ancestors=929538113,929538113)

**Comment by jimson-msft** [comment]
> Oops, forgot about it. I'll wait.
> 
> In reply to: [929538113](https://github.com/microsoft/do-client/pull/84#issuecomment-929538113)

Just checked the other PR in, this change looks good feel free to check in. I do notice reproducible failure with the plugin pipeline where the dpkg lock is already being held:
https://deliveryoptimization.visualstudio.com/client/_build/results?buildId=3423&view=logs&j=9d538be6-44f8-50c3-7930-4e7f88a0f6b2&t=4609d989-b212-5a4b-e936-e5e86def8716

Not sure what the cause is, it's happening on multiple agent machines as well

**Review by jimson-msft — APPROVED** [review]
:shipit:

**Comment by shishirb-MSFT** [comment]
Yeah I saw that and wasn't sure why it is happening only for the version updates. I'll dig deeper.

---
In reply to: [929730622](https://github.com/microsoft/do-client/pull/84#issuecomment-929730622) [](http://example.com/codeflow?ancestors=929730622,929730622)

**Comment by shishirb-MSFT** [comment]
Not seeing it anymore. Must be a transient issue with the VM.

---
In reply to: [929827600](https://github.com/microsoft/do-client/pull/84#issuecomment-929827600) [](http://example.com/codeflow?ancestors=929827600,929730622,929730622)

**Pull request merged**
