### PR TITLE
Add libcurl to NOTICE and cgmanifest

### PR DESCRIPTION
**Pull request by shishirb-MSFT**

### CODE REVIEW

**Comment by shishirb-MSFT** [comment]
@cmknox @jimson-msft The text in the NOTICE file was copied from https://curl.se/docs/copyright.html.
Is this the approach you took for the other libs as well?

**Comment by jimson-msft** [comment]
I believe so, Carmen to verify.

---
In reply to: [916693720](https://github.com/microsoft/do-client/pull/69#issuecomment-916693720) [](http://example.com/codeflow?ancestors=916693720,916693720)

**Review by jimson-msft — DISMISSED** [review]
:shipit:

**Review by jimson-msft — APPROVED** [review]
:shipit:

**Pull request merged**
